spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schedule?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
#  profiles:
#    active: test

mybatis-plus:
  configuration:
    # 关闭驼峰映射
    map-underscore-to-camel-case: false

server:
  port: 8088
